baseURL = "https://ananduee.github.io/"
languageCode = "en-us"
title = "Bad with names"
theme = "xmin"
pygmentsCodefences = true
pygmentsStyle = "tango"
customCodeStyle = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1