baseURL = "https://ananduee.github.io/"
languageCode = "en-us"
title = "Keep it simple, but not simpler"
theme = "xmin"
pygmentsCodefences = true
pygmentsStyle = "tango"
customCodeStyle = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1